events {
  worker_connections 1024;
}

http {
  upstream backend {
    server billing-service-mock-backend:3000;
  }

  server {
    listen 80;
    root /usr/share/nginx/html;
    index index.html;

    location /api {
      proxy_pass http://backend;
    }

    location / {
      try_files $uri $uri/ /index.html;
    }
  }
}